#!/bin/bash

NODES=10
START_PORT=1750
declare -i START_PORT
PID_DIR="run-dir"
HD_BIN="./hd"

if [ ! -x $HD_BIN ] ; then
   echo "Missing hash daemon: " $HD_BIN
   exit 1
fi

if [ ! -d $PID_DIR ] ; then
   mkdir $PID_DIR
fi

for i in `seq 1 1 $NODES` ; do

    pid_file="${PID_DIR}/hd-${i}.pid"

    # GOAL : check for an existing PID file and kill that daemons
    if [ -f $pid_file ] ; then
       pid=`cat $pid_file`
       echo "killing existing pid ${pid} on port ${START_PORT}"
       kill $pid
    fi

    # GOAL : start the hd daemon

    # FIXME : do something proper with STDERR
    $HD_BIN -p $START_PORT >/dev/null 2>&1 & disown
    echo $! > $pid_file
    echo "Started on port ${START_PORT}, pid ${!}"

    START_PORT+=1
done
